//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Managent_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentId { get; set; }
        public int ProjectId { get; set; }
        public int TaskId { get; set; }
        public int UserId { get; set; }
        public string Messaage { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Task Task { get; set; }
        public virtual Main_Users Main_Users { get; set; }
    }
}
