//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Managent_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Profiles
    {
        public int ProfileId { get; set; }
        public int UserId { get; set; }
        public string EmployeeId { get; set; }
        public string Department { get; set; }
        public string Designation { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string GitHubUrl { get; set; }
        public string LinkedInUrl { get; set; }
        public string PortfolioUrl { get; set; }
        public string TwitterUrl { get; set; }
        public string Bio { get; set; }
        public string Skills { get; set; }
        public string ProfilePicturePath { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    
        public virtual Main_Users Main_Users { get; set; }
    }
}
